name: Go

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: |
        export GO111MODULE=on
        export CGO_ENABLED=0
        export GOPROXY=https://proxy.golang.org
        go mod download
        go test -cover -vet all
        
    - name: Build
      run: |
        export GO111MODULE=on
        export CGO_ENABLED=0
        export GOPROXY=https://proxy.golang.org
        go build -a -ldflags "-X main.version=n/a -X main.rev=${GITHUB_SHA}"
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        
    - name: Build docker
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: dgrizzanti/drone-gke:latest
