name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

env:
  GO111MODULE: on
  CGO_ENABLED: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: |
        export GOPROXY=https://proxy.golang.org
        go mod download
        go test -cover -vet all
        
    - name: Build
      run: |
        export GOPROXY=https://proxy.golang.org
        echo "${GITHUB_REF_NAME}"
        go build -a -ldflags "-X main.version=${GITHUB_REF_NAME} -X main.rev=${GITHUB_SHA}"

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: dgrizzanti/drone-gke
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=ref,event=tag
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
