name: Go

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: |
        go mod download
        go test -cover -vet all
        
    - name: Build
      run: go build -a -ldflags "-X main.version=n/a -X main.rev=${GITHUB_SHA}"
